### ISSUE TITLE
Automatic body parsing

### ISSUE THREAD

**Issue by yereby** [sholladay/pogo#41]
Hello,
Is there a way to access the request payload like `request.payload` in hapi other than the one explained here https://github.com/sholladay/pogo#requestbody ?

**Comment by sholladay** [comment]
Not yet, I just haven't gotten around to adding automatic body parsing. It should be pretty easy to do though, if you'd like to make a PR.

**Comment by yereby** [comment]
Yes !
I just discover pogo, can you give we some insight ?

**Comment by sholladay** [comment]
Sure, well the first thing to do would be to write a test like the [request tests](https://github.com/sholladay/pogo/blob/master/test/request.js) that we have already. When we use `server.inject()` in those tests, we are basically making a fake [ServerRequest](https://github.com/denoland/deno/blob/2b0dc32718fb4891c788ca9a589ceea8095c1229/std/http/server.ts#L14-L114) object and giving it to the Pogo server as if it were a real HTTP request. You would do the same when making a test for `request.payload`.

The tests should check at least two cases:
 - When the `Content-Type` header is `application/json`, then `request.payload` must be a parsed JSON object
 - When the `Content-Type` header is any other value, then `request.payload` is a stream, same as `request.body`.

In the tests, you would pass an object to `server.inject()` that has a `body` property that conforms to the `Deno.Reader` interface (because that's how the `body` of the `ServerRequest` class works). An example of something like that is a [`StringReader`](https://github.com/denoland/deno/blob/2b0dc32718fb4891c788ca9a589ceea8095c1229/std/io/readers.ts#L9-L13). Should like roughly like this...

```js
const response = await server.inject({
    body : new StringReader(JSON.stringify({ foo : 'bar' }))
    // ...
});
```

After the tests are written, then the next step would be to add the automatic body parsing to the framework. I haven't thought too much about the architecture, but it would happen somewhere around this part of the code where we create our `request` object:
https://github.com/sholladay/pogo/blob/5a72c718b8aca97733540cc8ba13085eb69db020/lib/server.ts#L50-L54

It would be good to look into how hapi does this internally.

**Comment by sholladay** [comment]
Questions:
 - What should the TypeScript type be for `request.payload`? Could be something along the lines of `FormData | URLSearchParams | string | number | boolean | { [key: string]: any }` but I'm not sure if that's really helpful. Alternatively, it could be [`unknown`](https://www.typescriptlang.org/docs/handbook/2/functions.html#unknown), which would force you to assert its type when using it.  Or we could use a [generic type parameter](https://www.typescriptlang.org/docs/handbook/2/objects.html#generic-object-types), but I'm not sure exactly how it would work, I think you'd have to explicitly provide the expected type on the route handler or something.

**Comment by sholladay** [comment]
Until there is a concrete proposal for how to handle the TypeScript types, I am going to close this issue. Happy to reopen when it is more actionable.

FWIW, now that PR #68 has been merged, it is quite easy to parse the request body into various formats. For example, you can call `await request.raw.json()` to get the body as JSON. I'll probably add a shortcut in the future so you can skip the `.raw` and just do `await request.json()`, or similar for the other parsing methods.
