### ISSUE TITLE
[RFC] Additional metadata for readme examples?

### ISSUE THREAD

**Issue by afaur** [sholladay/pogo#43]
Might be helpful to link out to the code in readme examples.
Links would use a `tag` or `sha` to avoid taking the user to the latest changes. 
  - **Update**: This might introduce a lot of maintenance though, and I am not sure about it.

### [server](https://github.com/sholladay/pogo/blob/ffea1edec90a58a694b28c607d86653e91bd1efa/lib/server.ts#L28-L102).[router](https://github.com/sholladay/pogo/blob/ffea1edec90a58a694b28c607d86653e91bd1efa/lib/router.ts#L128-L357).[get](https://github.com/sholladay/pogo/blob/ffea1edec90a58a694b28c607d86653e91bd1efa/lib/router.ts#L258-L271)(String, [RouteHandler](https://github.com/sholladay/pogo/blob/ffea1edec90a58a694b28c607d86653e91bd1efa/lib/types.ts#L38)<[ServerRequest](https://github.com/sholladay/pogo/blob/ffea1edec90a58a694b28c607d86653e91bd1efa/lib/request.ts#L12-L59), [Toolkit](https://github.com/sholladay/pogo/blob/ffea1edec90a58a694b28c607d86653e91bd1efa/lib/toolkit.ts#L11-L34)>)
```js
// Javascript Example
server.router.get('/', (request, { file }) => {
    return file('./foo.jpg');
});
```
```ts
// Typescript Example
server.router.get('/', (request : ServerRequest, { file } : Toolkit) => {
    return file('./foo.jpg');
});
```

**Comment by sholladay** [comment]
Definitely would be useful, but a maintenance burden, as you said.

I think a more "cost effective" approach with roughly similar goals would be:
1. Improve our `deno doc` output and mention it in various places. Currently, `deno doc https://deno.land/x/pogo/main.ts` doesn't output anything. To fix this, I believe we need to export our classes as named exports and add doc comments to them.
2. Maybe re-export the types from `lib/types.ts` in `main.ts` to make them easier to discover and access?
3. Figure out why GitHub's link-to-definition feature isn't working for us. In most repositories, you can click on code within the README and it will show you its definition and references. It seems to work for most languages, including other Deno projects, but not here. Maybe because the source code is in `.ts` files but I've used `js` for the code fences in the docs? Perhaps the languages have to exactly match for GitHub to do its magic.

**Comment by afaur** [comment]
Opened (https://github.com/sholladay/pogo/pull/45) to work on items 1. and 2.
Will take a look at 3. soon.

**Comment by sholladay** [comment]
Looks like my theory about `3` was correct. I did a little experiment in PR #48 and changed a few of the code fences in the documentation to use "ts" instead of "js". Now the code in those examples is clickable, presumably because it matches the language of the source code.

For example, this one:
https://github.com/sholladay/pogo/tree/1e60ea963482070ff42e2b9da4c656223333e4c2#using-hdirectory-recommended

**Comment by sholladay** [comment]
I added TSDoc comments to further improve the `deno doc` output in commit https://github.com/sholladay/pogo/commit/8fa9c0c77be12cffc8a52cc8f51ad50c13366ab4. I also updated the language of the code examples in the documentation to enable GitHub's link-to-definition feature in commit https://github.com/sholladay/pogo/commit/4d24945730f5c4892bed90103be625e6189dd5d3.

With your PR, plus these changes, I think we can probably close this. What do you think?

I'm open to any other suggestions for improving the documentation. The next logical step I can think of would be to have a website for the docs.

**Comment by afaur** [comment]
The only other thing I can think of that may be good to add is a [![deno doc](https://doc.deno.land/badge.svg)](https://doc.deno.land/https/deno.land/x/pogo/main.ts) badge in the `README.md`.

**Comment by sholladay** [comment]
Thanks, good idea!

Done: https://github.com/sholladay/pogo/commit/fef521c0b065bb5da627d4e40780a0187312b441

**Comment by sholladay** [comment]
Pogo v0.5.0 has been published with these changes. Great work, @afaur!
