### ISSUE TITLE
Dynamic routes

### ISSUE THREAD

**Issue by victmo** [sholladay/pogo#5]
Is there a way to support dynamic routes?

Something like:
```js
server.route({
  method: 'GET',
  path: '/v2/users/{userId}/books',
  handler: (req, h) => {...}
})
```

**Comment by sholladay** [comment]
Not at the moment, but this is absolutely an important feature that I want to have.

We need to port [hapijs/call](https://github.com/hapijs/call) to Deno or otherwise build an improved router from scratch. At the moment, the routing logic is about as basic as it could possibly be. There are many features that I want the router to have, including preventing route conflicts.

Are you interested in helping with this?

**Comment by victmo** [comment]
Hi Seth,
Sorry for taking this long to answer.
I'd love to help, however, lately I don't have a lot of free time. I'll take a look at `call`, maybe its an easy port :)

**Comment by sholladay** [comment]
Just a minor update. I started writing my own router implementation from scratch - mostly as a learning exercise, but also so that `pogo` can use it if it turns out well or in case `hapijs/call` is difficult to port to Deno. I still think it would be good to use `call`, as that is a complex piece of code that is battle tested and it already has a lot of features that I probably won't be able to get around to in my own implementation anytime soon. Help on this would be much appreciated. But I should have a basic dynamic router in place within the next week or two.

**Comment by sholladay** [comment]
I added an improved router in https://github.com/sholladay/pogo/commit/9352e7905e95c5790d5f5f6944bc7bd0d9f4e4b2, which brings support for:
 - Simple path parameters of the `{userId}` variety (_required_ params)
 - Wildcard method handlers (`method: '*'` in route config)

There are still many improvements that should be made to the router. Among them, optional params and params that cover part of a segment or multiple segments are not yet supported. But it's a reasonable place to start and we can deal with the rest in separate issues. Let me know how it works for you!

**Comment by sholladay** [comment]
I just published a new release with these changes, as well as other routing improvements and bugfixes.

https://github.com/sholladay/pogo/releases/tag/v0.2.0
