### ISSUE TITLE
not able to run example : server.js 

### ISSUE THREAD

**Issue by vivekchauhan12000** [sholladay/pogo#57]
I have a question: I am trying to run the example  server.js which is throwing me these errors =

error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
    NamedStat
    ~~~~~~~~~
    at https://deno.land/x/pogo@v0.5.1/lib/util/read-dir-stats.ts:24:5

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { FileHandlerOptions } from './helpers/file.ts';
         ~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/pogo@v0.5.1/lib/types.ts:41:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { DirectoryHandlerOptions } from './helpers/directory.tsx';
         ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/pogo@v0.5.1/lib/types.ts:42:10

Found 3 errors.

**Comment by sholladay** [comment]
Hi @vivekchauhan12000, thanks for the bug report. This was fixed in commit https://github.com/sholladay/pogo/commit/ab8607467f4d023b8fe8a88531c41ec4c67c420a and I just published a new release, [v0.5.2](https://github.com/sholladay/pogo/releases/tag/v0.5.2), which contains the fix.

Since you tried to run the example with the old version, you probably still have that code in your cache. To force Deno to fetch the latest version and refresh the cache, use the `--reload` flag. Then it should work.

```sh
deno run -A --reload https://deno.land/x/pogo/example/simple-server/run.ts
```
